/*
 * Generated by XDoclet - Do not edit!
 */
package be.tba.ejb.mail.interfaces;

/**
 * Remote interface for MailerSession.
 * 
 * @xdoclet-generated at 1-01-15
 */
public interface MailerSession
{

    public void sendMail(java.sql.Connection con, java.lang.String fwdNumber);

}
