/*
 * Generated by XDoclet - Do not edit!
 */
package be.tba.ejb.account.interfaces;

/**
 * Data object for AccountEntity.
 *
 * @xdoclet-generated at 1-01-15
 */
public class AccountEntityData extends be.tba.util.data.AbstractData
// implements java.io.Serializable
{
    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private int id;
    private int wc_prime;
    private String wc_alfa;
    private java.lang.String userId;
    private java.lang.String password;
    private java.lang.String fwdNumber;
    private java.lang.String role;
    private java.lang.String fullName;
    private java.lang.String custFilter;
    private java.lang.String stateFilter;
    private java.lang.String dirFilter;
    private java.lang.String lastLogin;
    private long lastLoginTS;
    private long previousLoginTS;
    private boolean isRegistered;
    private boolean isAutoRelease;
    private boolean isXmlMail;
    private boolean is3W;
    private java.lang.String w3_PersonId;
    private java.lang.String w3_CompanyId;
    private java.lang.String email;
    private java.lang.String gsm;
    private short invoiceType;
    private long lastInvoiceTime;
    private long lastMailTime;
    private short mailHour1;
    private short mailMinutes1;
    private short mailHour2;
    private short mailMinutes2;
    private short mailHour3;
    private short mailMinutes3;
    private int facStdInCall;
    private int facStdOutCall;
    private int facOutLevel1;
    private int facOutLevel2;
    private int facOutLevel3;
    private boolean isPriceAgendaFixed;
    private int facAgendaCall;
    private int facFaxCall;
    private short agendaPriceUnit;
    private int facSms;
    private int facCallForward;
    private int taskHourRate;
    private java.lang.String companyName;
    private java.lang.String attToName;
    private java.lang.String street;
    private java.lang.String city;
    private java.lang.String btwNumber;
    private boolean noInvoice;
    private boolean hasSubCustomers;
    private java.lang.String superCustomer;
    private boolean countAllLongCalls;
    private boolean countLongFwdCalls;
    private boolean noBtw;
    private boolean noEmptyMails;
    private boolean textMail;
    private double facLong;
    private double facLongFwd;
    private int facTblMinCalls_I;
    private double facTblStartCost_I;
    private double facTblExtraCost_I;
    private int facTblMinCalls_II;
    private double facTblStartCost_II;
    private double facTblExtraCost_II;
    private int facTblMinCalls_III;
    private double facTblStartCost_III;
    private double facTblExtraCost_III;
    private int facTblMinCalls_IV;
    private double facTblStartCost_IV;
    private double facTblExtraCost_IV;
    private boolean isMailInvoice;
    private java.lang.String invoiceEmail;
    private java.lang.String accountNr;

    public AccountEntityData()
    {
    }

    public AccountEntityData(int id, int wc_prime, String wc_alfa, java.lang.String userId, java.lang.String password, java.lang.String fwdNumber, java.lang.String role, java.lang.String fullName, java.lang.String custFilter, java.lang.String stateFilter, java.lang.String dirFilter, java.lang.String lastLogin, long lastLoginTS, long previousLoginTS, boolean isRegistered, boolean isAutoRelease, boolean isXmlMail, boolean is3W, java.lang.String w3_PersonId, java.lang.String w3_CompanyId, java.lang.String email, java.lang.String gsm, short invoiceType, long lastInvoiceTime, long lastMailTime, short mailHour1, short mailMinutes1, short mailHour2, short mailMinutes2, short mailHour3, short mailMinutes3, int facStdInCall, int facStdOutCall, int facOutLevel1, int facOutLevel2, int facOutLevel3, boolean isPriceAgendaFixed, int facAgendaCall, int facFaxCall, short agendaPriceUnit, int facSms, int facCallForward, int taskHourRate, java.lang.String companyName, java.lang.String attToName, java.lang.String street, java.lang.String city, java.lang.String btwNumber, boolean noInvoice, boolean hasSubCustomers, java.lang.String superCustomer, boolean countAllLongCalls, boolean countLongFwdCalls, boolean noBtw, boolean noEmptyMails, boolean textMail, double facLong, double facLongFwd, int facTblMinCalls_I, double facTblStartCost_I, double facTblExtraCost_I, int facTblMinCalls_II, double facTblStartCost_II, double facTblExtraCost_II, int facTblMinCalls_III, double facTblStartCost_III, double facTblExtraCost_III, int facTblMinCalls_IV, double facTblStartCost_IV, double facTblExtraCost_IV, boolean isMailInvoice, java.lang.String invoiceEmail, java.lang.String accountNr)
    {
        setId(id);
        setWcPrime(wc_prime);
        setWcAlfa(wc_alfa);
        setUserId(userId);
        setPassword(password);
        setFwdNumber(fwdNumber);
        setRole(role);
        setFullName(fullName);
        setCustFilter(custFilter);
        setStateFilter(stateFilter);
        setDirFilter(dirFilter);
        setLastLogin(lastLogin);
        setLastLoginTS(lastLoginTS);
        setPreviousLoginTS(previousLoginTS);
        setIsRegistered(isRegistered);
        setIsAutoRelease(isAutoRelease);
        setIsXmlMail(isXmlMail);
        setIs3W(is3W);
        setW3_PersonId(w3_PersonId);
        setW3_CompanyId(w3_CompanyId);
        setEmail(email);
        setGsm(gsm);
        setInvoiceType(invoiceType);
        setLastInvoiceTime(lastInvoiceTime);
        setLastMailTime(lastMailTime);
        setMailHour1(mailHour1);
        setMailMinutes1(mailMinutes1);
        setMailHour2(mailHour2);
        setMailMinutes2(mailMinutes2);
        setMailHour3(mailHour3);
        setMailMinutes3(mailMinutes3);
        setFacStdInCall(facStdInCall);
        setFacStdOutCall(facStdOutCall);
        setFacOutLevel1(facOutLevel1);
        setFacOutLevel2(facOutLevel2);
        setFacOutLevel3(facOutLevel3);
        setIsPriceAgendaFixed(isPriceAgendaFixed);
        setFacAgendaCall(facAgendaCall);
        setFacFaxCall(facFaxCall);
        setAgendaPriceUnit(agendaPriceUnit);
        setFacSms(facSms);
        setFacCallForward(facCallForward);
        setTaskHourRate(taskHourRate);
        setCompanyName(companyName);
        setAttToName(attToName);
        setStreet(street);
        setCity(city);
        setBtwNumber(btwNumber);
        setNoInvoice(noInvoice);
        setHasSubCustomers(hasSubCustomers);
        setSuperCustomer(superCustomer);
        setCountAllLongCalls(countAllLongCalls);
        setCountLongFwdCalls(countLongFwdCalls);
        setNoBtw(noBtw);
        setNoEmptyMails(noEmptyMails);
        setTextMail(textMail);
        setFacLong(facLong);
        setFacLongFwd(facLongFwd);
        setFacTblMinCalls_I(facTblMinCalls_I);
        setFacTblStartCost_I(facTblStartCost_I);
        setFacTblExtraCost_I(facTblExtraCost_I);
        setFacTblMinCalls_II(facTblMinCalls_II);
        setFacTblStartCost_II(facTblStartCost_II);
        setFacTblExtraCost_II(facTblExtraCost_II);
        setFacTblMinCalls_III(facTblMinCalls_III);
        setFacTblStartCost_III(facTblStartCost_III);
        setFacTblExtraCost_III(facTblExtraCost_III);
        setFacTblMinCalls_IV(facTblMinCalls_IV);
        setFacTblStartCost_IV(facTblStartCost_IV);
        setFacTblExtraCost_IV(facTblExtraCost_IV);
        setIsMailInvoice(isMailInvoice);
        setInvoiceEmail(invoiceEmail);
        setAccountNr(accountNr);
    }

    public AccountEntityData(AccountEntityData otherData)
    {
        setId(otherData.getId());
        setWcPrime(otherData.getWcPrime());
        setWcAlfa(otherData.getWcAlfa());
        setUserId(otherData.getUserId());
        setPassword(otherData.getPassword());
        setFwdNumber(otherData.getFwdNumber());
        setRole(otherData.getRole());
        setFullName(otherData.getFullName());
        setCustFilter(otherData.getCustFilter());
        setStateFilter(otherData.getStateFilter());
        setDirFilter(otherData.getDirFilter());
        setLastLogin(otherData.getLastLogin());
        setLastLoginTS(otherData.getLastLoginTS());
        setPreviousLoginTS(otherData.getPreviousLoginTS());
        setIsRegistered(otherData.getIsRegistered());
        setIsAutoRelease(otherData.getIsAutoRelease());
        setIsXmlMail(otherData.getIsXmlMail());
        setIs3W(otherData.getIs3W());
        setW3_PersonId(otherData.getW3_PersonId());
        setW3_CompanyId(otherData.getW3_CompanyId());
        setEmail(otherData.getEmail());
        setInvoiceEmail(otherData.getInvoiceEmail());
        setGsm(otherData.getGsm());
        setInvoiceType(otherData.getInvoiceType());
        setLastInvoiceTime(otherData.getLastInvoiceTime());
        setLastMailTime(otherData.getLastMailTime());
        setMailHour1(otherData.getMailHour1());
        setMailMinutes1(otherData.getMailMinutes1());
        setMailHour2(otherData.getMailHour2());
        setMailMinutes2(otherData.getMailMinutes2());
        setMailHour3(otherData.getMailHour3());
        setMailMinutes3(otherData.getMailMinutes3());
        setFacStdInCall(otherData.getFacStdInCall());
        setFacStdOutCall(otherData.getFacStdOutCall());
        setFacOutLevel1(otherData.getFacOutLevel1());
        setFacOutLevel2(otherData.getFacOutLevel2());
        setFacOutLevel3(otherData.getFacOutLevel3());
        setIsPriceAgendaFixed(otherData.getIsPriceAgendaFixed());
        setFacAgendaCall(otherData.getFacAgendaCall());
        setFacFaxCall(otherData.getFacFaxCall());
        setAgendaPriceUnit(otherData.getAgendaPriceUnit());
        setFacSms(otherData.getFacSms());
        setFacCallForward(otherData.getFacCallForward());
        setTaskHourRate(otherData.getTaskHourRate());
        setCompanyName(otherData.getCompanyName());
        setAttToName(otherData.getAttToName());
        setStreet(otherData.getStreet());
        setCity(otherData.getCity());
        setBtwNumber(otherData.getBtwNumber());
        setNoInvoice(otherData.getNoInvoice());
        setHasSubCustomers(otherData.getHasSubCustomers());
        setSuperCustomer(otherData.getSuperCustomer());
        setCountAllLongCalls(otherData.getCountAllLongCalls());
        setCountLongFwdCalls(otherData.getCountLongFwdCalls());
        setNoBtw(otherData.getNoBtw());
        setNoEmptyMails(otherData.getNoEmptyMails());
        setTextMail(otherData.getTextMail());
        setFacLong(otherData.getFacLong());
        setFacLongFwd(otherData.getFacLongFwd());
        setFacTblMinCalls_I(otherData.getFacTblMinCalls_I());
        setFacTblStartCost_I(otherData.getFacTblStartCost_I());
        setFacTblExtraCost_I(otherData.getFacTblExtraCost_I());
        setFacTblMinCalls_II(otherData.getFacTblMinCalls_II());
        setFacTblStartCost_II(otherData.getFacTblStartCost_II());
        setFacTblExtraCost_II(otherData.getFacTblExtraCost_II());
        setFacTblMinCalls_III(otherData.getFacTblMinCalls_III());
        setFacTblStartCost_III(otherData.getFacTblStartCost_III());
        setFacTblExtraCost_III(otherData.getFacTblExtraCost_III());
        setFacTblMinCalls_IV(otherData.getFacTblMinCalls_IV());
        setFacTblStartCost_IV(otherData.getFacTblStartCost_IV());
        setFacTblExtraCost_IV(otherData.getFacTblExtraCost_IV());
        setIsMailInvoice(otherData.getIsMailInvoice());
        setAccountNr(otherData.getAccountNr());

    }

    public AccountEntityPK getPrimaryKey()
    {
        return new AccountEntityPK(this.getId());
    }

    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public int getWcPrime()
    {
        return this.wc_prime;
    }

    public void setWcPrime(int wc_prime)
    {
        this.wc_prime = wc_prime;
    }

    public java.lang.String getWcAlfa()
    {
        return this.wc_alfa;
    }

    public void setWcAlfa(java.lang.String wc_alfa)
    {
        this.wc_alfa = wc_alfa;
    }

    public java.lang.String getUserId()
    {
        return this.userId;
    }

    public void setUserId(java.lang.String userId)
    {
        this.userId = userId;
    }

    public java.lang.String getPassword()
    {
        return this.password;
    }

    public void setPassword(java.lang.String password)
    {
        this.password = password;
    }

    public java.lang.String getFwdNumber()
    {
        return this.fwdNumber;
    }

    public void setFwdNumber(java.lang.String fwdNumber)
    {
        this.fwdNumber = fwdNumber;
    }

    public java.lang.String getRole()
    {
        return this.role;
    }

    public void setRole(java.lang.String role)
    {
        this.role = role;
    }

    public java.lang.String getFullName()
    {
        return this.fullName;
    }

    public void setFullName(java.lang.String fullName)
    {
        this.fullName = fullName;
    }

    public java.lang.String getCustFilter()
    {
        return this.custFilter;
    }

    public void setCustFilter(java.lang.String custFilter)
    {
        this.custFilter = custFilter;
    }

    public java.lang.String getStateFilter()
    {
        return this.stateFilter;
    }

    public void setStateFilter(java.lang.String stateFilter)
    {
        this.stateFilter = stateFilter;
    }

    public java.lang.String getDirFilter()
    {
        return this.dirFilter;
    }

    public void setDirFilter(java.lang.String dirFilter)
    {
        this.dirFilter = dirFilter;
    }

    public java.lang.String getLastLogin()
    {
        return this.lastLogin;
    }

    public void setLastLogin(java.lang.String lastLogin)
    {
        this.lastLogin = lastLogin;
    }

    public long getLastLoginTS()
    {
        return this.lastLoginTS;
    }

    public void setLastLoginTS(long lastLoginTS)
    {
        this.lastLoginTS = lastLoginTS;
    }

    public long getPreviousLoginTS()
    {
        return this.previousLoginTS;
    }

    public void setPreviousLoginTS(long previousLoginTS)
    {
        this.previousLoginTS = previousLoginTS;
    }

    public boolean getIsRegistered()
    {
        return this.isRegistered;
    }

    public void setIsRegistered(boolean isRegistered)
    {
        this.isRegistered = isRegistered;
    }

    public boolean getIsAutoRelease()
    {
        return this.isAutoRelease;
    }

    public void setIsAutoRelease(boolean isAutoRelease)
    {
        this.isAutoRelease = isAutoRelease;
    }

    public boolean getIsXmlMail()
    {
        return this.isXmlMail;
    }

    public void setIsXmlMail(boolean isXmlMail)
    {
        this.isXmlMail = isXmlMail;
    }

    public boolean getIs3W()
    {
        return this.is3W;
    }

    public void setIs3W(boolean is3W)
    {
        this.is3W = is3W;
    }

    public java.lang.String getW3_PersonId()
    {
        return this.w3_PersonId;
    }

    public void setW3_PersonId(java.lang.String w3_PersonId)
    {
        this.w3_PersonId = w3_PersonId;
    }

    public java.lang.String getW3_CompanyId()
    {
        return this.w3_CompanyId;
    }

    public void setW3_CompanyId(java.lang.String w3_CompanyId)
    {
        this.w3_CompanyId = w3_CompanyId;
    }

    public java.lang.String getEmail()
    {
        return this.email;
    }

    public void setEmail(java.lang.String email)
    {
        this.email = email;
    }

    public java.lang.String getInvoiceEmail()
    {
        return this.invoiceEmail;
    }

    public void setInvoiceEmail(java.lang.String invoiceEmail)
    {
        this.invoiceEmail = invoiceEmail;
    }

    public java.lang.String getGsm()
    {
        return this.gsm;
    }

    public void setGsm(java.lang.String gsm)
    {
        this.gsm = gsm;
    }

    public short getInvoiceType()
    {
        return this.invoiceType;
    }

    public void setInvoiceType(short invoiceType)
    {
        this.invoiceType = invoiceType;
    }

    public long getLastInvoiceTime()
    {
        return this.lastInvoiceTime;
    }

    public void setLastInvoiceTime(long lastInvoiceTime)
    {
        this.lastInvoiceTime = lastInvoiceTime;
    }

    public long getLastMailTime()
    {
        return this.lastMailTime;
    }

    public void setLastMailTime(long lastMailTime)
    {
        this.lastMailTime = lastMailTime;
    }

    public short getMailHour1()
    {
        return this.mailHour1;
    }

    public void setMailHour1(short mailHour1)
    {
        this.mailHour1 = mailHour1;
    }

    public short getMailMinutes1()
    {
        return this.mailMinutes1;
    }

    public void setMailMinutes1(short mailMinutes1)
    {
        this.mailMinutes1 = mailMinutes1;
    }

    public short getMailHour2()
    {
        return this.mailHour2;
    }

    public void setMailHour2(short mailHour2)
    {
        this.mailHour2 = mailHour2;
    }

    public short getMailMinutes2()
    {
        return this.mailMinutes2;
    }

    public void setMailMinutes2(short mailMinutes2)
    {
        this.mailMinutes2 = mailMinutes2;
    }

    public short getMailHour3()
    {
        return this.mailHour3;
    }

    public void setMailHour3(short mailHour3)
    {
        this.mailHour3 = mailHour3;
    }

    public short getMailMinutes3()
    {
        return this.mailMinutes3;
    }

    public void setMailMinutes3(short mailMinutes3)
    {
        this.mailMinutes3 = mailMinutes3;
    }

    public int getFacStdInCall()
    {
        return this.facStdInCall;
    }

    public void setFacStdInCall(int facStdInCall)
    {
        this.facStdInCall = facStdInCall;
    }

    public int getFacStdOutCall()
    {
        return this.facStdOutCall;
    }

    public void setFacStdOutCall(int facStdOutCall)
    {
        this.facStdOutCall = facStdOutCall;
    }

    public int getFacOutLevel1()
    {
        return this.facOutLevel1;
    }

    public void setFacOutLevel1(int facOutLevel1)
    {
        this.facOutLevel1 = facOutLevel1;
    }

    public int getFacOutLevel2()
    {
        return this.facOutLevel2;
    }

    public void setFacOutLevel2(int facOutLevel2)
    {
        this.facOutLevel2 = facOutLevel2;
    }

    public int getFacOutLevel3()
    {
        return this.facOutLevel3;
    }

    public void setFacOutLevel3(int facOutLevel3)
    {
        this.facOutLevel3 = facOutLevel3;
    }

    public boolean getIsPriceAgendaFixed()
    {
        return this.isPriceAgendaFixed;
    }

    public void setIsPriceAgendaFixed(boolean isPriceAgendaFixed)
    {
        this.isPriceAgendaFixed = isPriceAgendaFixed;
    }

    public int getFacAgendaCall()
    {
        return this.facAgendaCall;
    }

    public void setFacAgendaCall(int facAgendaCall)
    {
        this.facAgendaCall = facAgendaCall;
    }

    public int getFacFaxCall()
    {
        return this.facFaxCall;
    }

    public void setFacFaxCall(int facFaxCall)
    {
        this.facFaxCall = facFaxCall;
    }

    public short getAgendaPriceUnit()
    {
        return this.agendaPriceUnit;
    }

    public void setAgendaPriceUnit(short agendaPriceUnit)
    {
        this.agendaPriceUnit = agendaPriceUnit;
    }

    public int getFacSms()
    {
        return this.facSms;
    }

    public void setFacSms(int facSms)
    {
        this.facSms = facSms;
    }

    public int getFacCallForward()
    {
        return this.facCallForward;
    }

    public void setFacCallForward(int facCallForward)
    {
        this.facCallForward = facCallForward;
    }

    public int getTaskHourRate()
    {
        return this.taskHourRate;
    }

    public void setTaskHourRate(int taskHourRate)
    {
        this.taskHourRate = taskHourRate;
    }

    public java.lang.String getCompanyName()
    {
        return this.companyName;
    }

    public void setCompanyName(java.lang.String companyName)
    {
        this.companyName = companyName;
    }

    public java.lang.String getAttToName()
    {
        return this.attToName;
    }

    public void setAttToName(java.lang.String attToName)
    {
        this.attToName = attToName;
    }

    public java.lang.String getStreet()
    {
        return this.street;
    }

    public void setStreet(java.lang.String street)
    {
        this.street = street;
    }

    public java.lang.String getCity()
    {
        return this.city;
    }

    public void setCity(java.lang.String city)
    {
        this.city = city;
    }

    public java.lang.String getBtwNumber()
    {
        return this.btwNumber;
    }

    public void setBtwNumber(java.lang.String btwNumber)
    {
        this.btwNumber = btwNumber;
    }

    public boolean getNoInvoice()
    {
        return this.noInvoice;
    }

    public void setNoInvoice(boolean noInvoice)
    {
        this.noInvoice = noInvoice;
    }

    public boolean getHasSubCustomers()
    {
        return this.hasSubCustomers;
    }

    public void setHasSubCustomers(boolean hasSubCustomers)
    {
        this.hasSubCustomers = hasSubCustomers;
    }

    public java.lang.String getSuperCustomer()
    {
        return this.superCustomer;
    }

    public void setSuperCustomer(java.lang.String superCustomer)
    {
        this.superCustomer = superCustomer;
    }

    public java.lang.String getAccountNr()
    {
        return this.accountNr;
    }

    public void setAccountNr(java.lang.String accountNr)
    {
        this.accountNr = accountNr;
    }

    public boolean getCountAllLongCalls()
    {
        return this.countAllLongCalls;
    }

    public void setCountAllLongCalls(boolean countAllLongCalls)
    {
        this.countAllLongCalls = countAllLongCalls;
    }

    public boolean getCountLongFwdCalls()
    {
        return this.countLongFwdCalls;
    }

    public void setCountLongFwdCalls(boolean countLongFwdCalls)
    {
        this.countLongFwdCalls = countLongFwdCalls;
    }

    public boolean getNoBtw()
    {
        return this.noBtw;
    }

    public void setNoBtw(boolean noBtw)
    {
        this.noBtw = noBtw;
    }

    public boolean getNoEmptyMails()
    {
        return this.noEmptyMails;
    }

    public void setNoEmptyMails(boolean noEmptyMails)
    {
        this.noEmptyMails = noEmptyMails;
    }

    public boolean getTextMail()
    {
        return this.textMail;
    }

    public void setTextMail(boolean textMail)
    {
        this.textMail = textMail;
    }

    public double getFacLong()
    {
        return this.facLong;
    }

    public void setFacLong(double facLong)
    {
        this.facLong = facLong;
    }

    public double getFacLongFwd()
    {
        return this.facLongFwd;
    }

    public void setFacLongFwd(double facLongFwd)
    {
        this.facLongFwd = facLongFwd;
    }

    public int getFacTblMinCalls_I()
    {
        return this.facTblMinCalls_I;
    }

    public void setFacTblMinCalls_I(int facTblMinCalls_I)
    {
        this.facTblMinCalls_I = facTblMinCalls_I;
    }

    public double getFacTblStartCost_I()
    {
        return this.facTblStartCost_I;
    }

    public void setFacTblStartCost_I(double facTblStartCost_I)
    {
        this.facTblStartCost_I = facTblStartCost_I;
    }

    public double getFacTblExtraCost_I()
    {
        return this.facTblExtraCost_I;
    }

    public void setFacTblExtraCost_I(double facTblExtraCost_I)
    {
        this.facTblExtraCost_I = facTblExtraCost_I;
    }

    public int getFacTblMinCalls_II()
    {
        return this.facTblMinCalls_II;
    }

    public void setFacTblMinCalls_II(int facTblMinCalls_II)
    {
        this.facTblMinCalls_II = facTblMinCalls_II;
    }

    public double getFacTblStartCost_II()
    {
        return this.facTblStartCost_II;
    }

    public void setFacTblStartCost_II(double facTblStartCost_II)
    {
        this.facTblStartCost_II = facTblStartCost_II;
    }

    public double getFacTblExtraCost_II()
    {
        return this.facTblExtraCost_II;
    }

    public void setFacTblExtraCost_II(double facTblExtraCost_II)
    {
        this.facTblExtraCost_II = facTblExtraCost_II;
    }

    public int getFacTblMinCalls_III()
    {
        return this.facTblMinCalls_III;
    }

    public void setFacTblMinCalls_III(int facTblMinCalls_III)
    {
        this.facTblMinCalls_III = facTblMinCalls_III;
    }

    public double getFacTblStartCost_III()
    {
        return this.facTblStartCost_III;
    }

    public void setFacTblStartCost_III(double facTblStartCost_III)
    {
        this.facTblStartCost_III = facTblStartCost_III;
    }

    public double getFacTblExtraCost_III()
    {
        return this.facTblExtraCost_III;
    }

    public void setFacTblExtraCost_III(double facTblExtraCost_III)
    {
        this.facTblExtraCost_III = facTblExtraCost_III;
    }

    public int getFacTblMinCalls_IV()
    {
        return this.facTblMinCalls_IV;
    }

    public void setFacTblMinCalls_IV(int facTblMinCalls_IV)
    {
        this.facTblMinCalls_IV = facTblMinCalls_IV;
    }

    public double getFacTblStartCost_IV()
    {
        return this.facTblStartCost_IV;
    }

    public void setFacTblStartCost_IV(double facTblStartCost_IV)
    {
        this.facTblStartCost_IV = facTblStartCost_IV;
    }

    public double getFacTblExtraCost_IV()
    {
        return this.facTblExtraCost_IV;
    }

    public void setFacTblExtraCost_IV(double facTblExtraCost_IV)
    {
        this.facTblExtraCost_IV = facTblExtraCost_IV;
    }

    public boolean getIsMailInvoice()
    {
        return this.isMailInvoice;
    }

    public void setIsMailInvoice(boolean isMailInvoice)
    {
        this.isMailInvoice = isMailInvoice;
    }

    public String toString()
    {
        StringBuffer str = new StringBuffer("{");

        str.append(toNameValueString().toString());
        str.append('}');

        return (str.toString());
    }

    public String toNameValueString()
    {
        StringBuffer str = new StringBuffer();

        str.append("WC_Prime=");
        str.append(this.wc_prime);
        str.append(",WC_Alfa='");
        str.append(((this.wc_alfa != null) ? this.wc_alfa : ""));
        str.append("',UserId='");
        str.append(((this.userId != null) ? this.userId : ""));
        str.append("',Password='");
        str.append(((this.password != null) ? this.password : ""));
        str.append("',FwdNumber='");
        str.append(((this.fwdNumber != null) ? this.fwdNumber : ""));
        str.append("',Role='");
        str.append(((this.role != null) ? this.role : ""));
        str.append("',FullName='");
        str.append(((this.fullName != null) ? escapeQuotes(this.fullName) : ""));
        str.append("',CustFilter='");
        str.append(((this.custFilter != null) ? this.custFilter : ""));
        str.append("',StateFilter='");
        str.append(((this.stateFilter != null) ? this.stateFilter : ""));
        str.append("',DirFilter='");
        str.append(((this.dirFilter != null) ? this.dirFilter : ""));
        str.append("',LastLogin='");
        str.append(((this.lastLogin != null) ? this.lastLogin : ""));
        str.append("',LastLoginTS=");
        str.append(getLastLoginTS());
        str.append(",PrevLoginTS=");
        str.append(getPreviousLoginTS());
        str.append(",IsRegistered=");
        str.append(getIsRegistered());
        str.append(",IsAutoRelease=");
        str.append(getIsAutoRelease());
        str.append(",IsXmlMail=");
        str.append(getIsXmlMail());
        str.append(",Is3W=");
        str.append(getIs3W());
        str.append(",W3_PersonId='");
        str.append(((this.w3_PersonId != null) ? this.w3_PersonId : ""));
        str.append("',W3_CompanyId='");
        str.append(((this.w3_CompanyId != null) ? this.w3_CompanyId : ""));
        str.append("',Email='");
        str.append(((this.email != null) ? this.email : ""));
        str.append("',Gsm='");
        str.append(((this.gsm != null) ? escapeQuotes(this.gsm) : ""));
        str.append("',InvoiceType=");
        str.append(getInvoiceType());
        str.append(",LastInvoiceTime=");
        str.append(getLastInvoiceTime());
        str.append(",LastMailTime=");
        str.append(getLastMailTime());
        str.append(",MailHour1=");
        str.append(getMailHour1());
        str.append(",MailMinutes1=");
        str.append(getMailMinutes1());
        str.append(",MailHour2=");
        str.append(getMailHour2());
        str.append(",MailMinutes2=");
        str.append(getMailMinutes2());
        str.append(",MailHour3=");
        str.append(getMailHour3());
        str.append(",MailMinutes3=");
        str.append(getMailMinutes3());
        str.append(",FacStdInCall=");
        str.append(getFacStdInCall());
        str.append(",FacOutLevel1=");
        str.append(getFacOutLevel1());
        str.append(",FacOutLevel2=");
        str.append(getFacOutLevel2());
        str.append(",FacOutLevel3=");
        str.append(getFacOutLevel3());
        str.append(",IsPriceAgendaFixed=");
        str.append(getIsPriceAgendaFixed());
        str.append(",FacAgendaCall=");
        str.append(getFacAgendaCall());
        str.append(",AgendaPriceUnit=");
        str.append(getAgendaPriceUnit());
        str.append(",FacSms=");
        str.append(getFacSms());
        str.append(",FacCallForward=");
        str.append(getFacCallForward());
        str.append(",FacStdOutCall=");
        str.append(getFacStdOutCall());
        str.append(",TaskHourRate=");
        str.append(getTaskHourRate());
        str.append(",CompanyName='");
        str.append(((this.companyName != null) ? escapeQuotes(this.companyName) : ""));
        str.append("',AttToName='");
        str.append(((this.attToName != null) ? escapeQuotes(this.attToName) : ""));
        str.append("',Street='");
        str.append(((this.street != null) ? escapeQuotes(this.street) : ""));
        str.append("',City='");
        str.append(((this.city != null) ? this.city : ""));
        str.append("',BtwNumber='");
        str.append(((this.btwNumber != null) ? this.btwNumber : ""));
        str.append("',NoInvoice=");
        str.append(getNoInvoice());
        str.append(",FacFaxCall=");
        str.append(getFacFaxCall());
        str.append(",HasSubCustomers=");
        str.append(getHasSubCustomers());
        str.append(",SuperCustomer='");
        str.append(((this.superCustomer != null) ? this.superCustomer : ""));
        str.append("',CountAllLongCalls=");
        str.append(getCountAllLongCalls());
        str.append(",CountLongFwdCalls=");
        str.append(getCountLongFwdCalls());
        str.append(",NoBtw=");
        str.append(getNoBtw());
        str.append(",NoEmptyMails=");
        str.append(getNoEmptyMails());
        str.append(",TextMail=");
        str.append(getTextMail());
        str.append(",FacLong=");
        str.append(getFacLong());
        str.append(",FacLongFwd=");
        str.append(getFacLongFwd());
        str.append(",FacTblMinCalls_I=");
        str.append(getFacTblMinCalls_I());
        str.append(",FacTblMinCalls_II=");
        str.append(getFacTblMinCalls_II());
        str.append(",FacTblMinCalls_III=");
        str.append(getFacTblMinCalls_III());
        str.append(",FacTblMinCalls_IV=");
        str.append(getFacTblMinCalls_IV());
        str.append(",FacTblStartCost_I=");
        str.append(getFacTblStartCost_I());
        str.append(",FacTblStartCost_II=");
        str.append(getFacTblStartCost_II());
        str.append(",FacTblStartCost_III=");
        str.append(getFacTblStartCost_III());
        str.append(",FacTblStartCost_IV=");
        str.append(getFacTblStartCost_IV());
        str.append(",FacTblExtraCost_I=");
        str.append(getFacTblExtraCost_I());
        str.append(",FacTblExtraCost_II=");
        str.append(getFacTblExtraCost_II());
        str.append(",FacTblExtraCost_III=");
        str.append(getFacTblExtraCost_III());
        str.append(",FacTblExtraCost_IV=");
        str.append(getFacTblExtraCost_IV());
        str.append(",IsMailInvoice=");
        str.append(getIsMailInvoice());
        str.append(",InvoiceEmail='");
        str.append(((this.invoiceEmail != null) ? this.invoiceEmail : ""));
        str.append("',AccountNr='");
        str.append(((this.accountNr != null) ? escapeQuotes(this.accountNr) : ""));
        str.append("' ");
        return (str.toString());

    }

    public String toValueString()
    {
        StringBuffer str = new StringBuffer();

        // "(1, '409031', '04/10/05', 1128528272192, 1, 220, 0, 'Nabelactie voor
        // client'. ',0 ,0 ,0 ,0 ,'')
        str.append("'0','");
        str.append(((this.userId != null) ? this.userId : ""));
        str.append("','");
        str.append(((this.password != null) ? this.password : ""));
        str.append("','");
        str.append(((this.fwdNumber != null) ? this.fwdNumber : ""));
        str.append("','");
        str.append(((this.role != null) ? this.role : ""));
        str.append("','");
        str.append(((this.fullName != null) ? this.fullName : ""));
        str.append("','");
        str.append(((this.custFilter != null) ? this.custFilter : ""));
        str.append("','");
        str.append(((this.stateFilter != null) ? this.stateFilter : ""));
        str.append("','");
        str.append(((this.dirFilter != null) ? this.dirFilter : ""));
        str.append("','");
        str.append(((this.lastLogin != null) ? this.lastLogin : ""));
        str.append("',");
        str.append(getLastLoginTS());
        str.append(",");
        str.append(getPreviousLoginTS());
        str.append(",");
        str.append(getIsRegistered());
        str.append(",");
        str.append(getIsAutoRelease());
        str.append(",");
        str.append(getIsXmlMail());
        str.append(",");
        str.append(getIs3W());
        str.append(",'");
        str.append(((this.w3_PersonId != null) ? this.w3_PersonId : ""));
        str.append("','");
        str.append(((this.w3_CompanyId != null) ? this.w3_CompanyId : ""));
        str.append("','");
        str.append(((this.email != null) ? this.email : ""));
        str.append("','");
        str.append(((this.gsm != null) ? this.gsm : ""));
        str.append("',");
        str.append(getInvoiceType());
        str.append(",");
        str.append(getLastInvoiceTime());
        str.append(",");
        str.append(getLastMailTime());
        str.append(",");
        str.append(getMailHour1());
        str.append(",");
        str.append(getMailMinutes1());
        str.append(",");
        str.append(getMailHour2());
        str.append(",");
        str.append(getMailMinutes2());
        str.append(",");
        str.append(getMailHour3());
        str.append(",");
        str.append(getMailMinutes3());
        str.append(",");
        str.append(getFacStdInCall());
        str.append(",");
        str.append(getFacOutLevel1());
        str.append(",");
        str.append(getFacOutLevel2());
        str.append(",");
        str.append(getFacOutLevel3());
        str.append(",");
        str.append(getIsPriceAgendaFixed());
        str.append(",");
        str.append(getFacAgendaCall());
        str.append(",");
        str.append(getAgendaPriceUnit());
        str.append(",");
        str.append(getFacSms());
        str.append(",");
        str.append(getFacCallForward());
        str.append(",");
        str.append(getFacStdOutCall());
        str.append(",");
        str.append(getTaskHourRate());
        str.append(",'");
        str.append(((this.companyName != null) ? this.companyName : ""));
        str.append("','");
        str.append(((this.attToName != null) ? this.attToName : ""));
        str.append("','");
        str.append(((this.street != null) ? this.street : ""));
        str.append("','");
        str.append(((this.city != null) ? this.city : ""));
        str.append("','");
        str.append(((this.btwNumber != null) ? this.btwNumber : ""));
        str.append("',");
        str.append(getNoInvoice());
        str.append(",");
        str.append(getFacFaxCall());
        str.append(",");
        str.append(getHasSubCustomers());
        str.append(",'");
        str.append(((this.superCustomer != null) ? this.superCustomer : ""));
        str.append("',");
        str.append(getCountAllLongCalls());
        str.append(",");
        str.append(getCountLongFwdCalls());
        str.append(",");
        str.append(getNoBtw());
        str.append(",");
        str.append(getNoEmptyMails());
        str.append(",");
        str.append(getTextMail());
        str.append(",");
        str.append(getFacLong());
        str.append(",");
        str.append(getFacLongFwd());
        str.append(",");
        str.append(getFacTblMinCalls_I());
        str.append(",");
        str.append(getFacTblMinCalls_II());
        str.append(",");
        str.append(getFacTblMinCalls_III());
        str.append(",");
        str.append(getFacTblMinCalls_IV());
        str.append(",");
        str.append(getFacTblStartCost_I());
        str.append(",");
        str.append(getFacTblStartCost_II());
        str.append(",");
        str.append(getFacTblStartCost_III());
        str.append(",");
        str.append(getFacTblStartCost_IV());
        str.append(",");
        str.append(getFacTblExtraCost_I());
        str.append(",");
        str.append(getFacTblExtraCost_II());
        str.append(",");
        str.append(getFacTblExtraCost_III());
        str.append(",");
        str.append(getFacTblExtraCost_IV());
        str.append(",");
        str.append(getIsMailInvoice());
        str.append(",'");
        str.append(((this.invoiceEmail != null) ? this.invoiceEmail : ""));
        str.append("','");
        str.append(((this.accountNr != null) ? escapeQuotes(this.accountNr) : ""));
        str.append("'");
        return (str.toString());
    }

    public boolean equals(Object pOther)
    {
        if (pOther instanceof AccountEntityData)
        {
            AccountEntityData lTest = (AccountEntityData) pOther;
            boolean lEquals = true;

            lEquals = lEquals && this.id == lTest.id;
            if (this.userId == null)
            {
                lEquals = lEquals && (lTest.userId == null);
            }
            else
            {
                lEquals = lEquals && this.userId.equals(lTest.userId);
            }
            if (this.password == null)
            {
                lEquals = lEquals && (lTest.password == null);
            }
            else
            {
                lEquals = lEquals && this.password.equals(lTest.password);
            }
            if (this.fwdNumber == null)
            {
                lEquals = lEquals && (lTest.fwdNumber == null);
            }
            else
            {
                lEquals = lEquals && this.fwdNumber.equals(lTest.fwdNumber);
            }
            if (this.role == null)
            {
                lEquals = lEquals && (lTest.role == null);
            }
            else
            {
                lEquals = lEquals && this.role.equals(lTest.role);
            }
            if (this.fullName == null)
            {
                lEquals = lEquals && (lTest.fullName == null);
            }
            else
            {
                lEquals = lEquals && this.fullName.equals(lTest.fullName);
            }
            if (this.custFilter == null)
            {
                lEquals = lEquals && (lTest.custFilter == null);
            }
            else
            {
                lEquals = lEquals && this.custFilter.equals(lTest.custFilter);
            }
            if (this.stateFilter == null)
            {
                lEquals = lEquals && (lTest.stateFilter == null);
            }
            else
            {
                lEquals = lEquals && this.stateFilter.equals(lTest.stateFilter);
            }
            if (this.dirFilter == null)
            {
                lEquals = lEquals && (lTest.dirFilter == null);
            }
            else
            {
                lEquals = lEquals && this.dirFilter.equals(lTest.dirFilter);
            }
            if (this.lastLogin == null)
            {
                lEquals = lEquals && (lTest.lastLogin == null);
            }
            else
            {
                lEquals = lEquals && this.lastLogin.equals(lTest.lastLogin);
            }
            lEquals = lEquals && this.lastLoginTS == lTest.lastLoginTS;
            lEquals = lEquals && this.previousLoginTS == lTest.previousLoginTS;
            lEquals = lEquals && this.isRegistered == lTest.isRegistered;
            lEquals = lEquals && this.isAutoRelease == lTest.isAutoRelease;
            lEquals = lEquals && this.isXmlMail == lTest.isXmlMail;
            lEquals = lEquals && this.is3W == lTest.is3W;
            if (this.w3_PersonId == null)
            {
                lEquals = lEquals && (lTest.w3_PersonId == null);
            }
            else
            {
                lEquals = lEquals && this.w3_PersonId.equals(lTest.w3_PersonId);
            }
            if (this.w3_CompanyId == null)
            {
                lEquals = lEquals && (lTest.w3_CompanyId == null);
            }
            else
            {
                lEquals = lEquals && this.w3_CompanyId.equals(lTest.w3_CompanyId);
            }
            if (this.email == null)
            {
                lEquals = lEquals && (lTest.email == null);
            }
            else
            {
                lEquals = lEquals && this.email.equals(lTest.email);
            }
            if (this.invoiceEmail == null)
            {
                lEquals = lEquals && (lTest.invoiceEmail == null);
            }
            else
            {
                lEquals = lEquals && this.invoiceEmail.equals(lTest.invoiceEmail);
            }
            if (this.gsm == null)
            {
                lEquals = lEquals && (lTest.gsm == null);
            }
            else
            {
                lEquals = lEquals && this.gsm.equals(lTest.gsm);
            }
            lEquals = lEquals && this.invoiceType == lTest.invoiceType;
            lEquals = lEquals && this.lastInvoiceTime == lTest.lastInvoiceTime;
            lEquals = lEquals && this.lastMailTime == lTest.lastMailTime;
            lEquals = lEquals && this.mailHour1 == lTest.mailHour1;
            lEquals = lEquals && this.mailMinutes1 == lTest.mailMinutes1;
            lEquals = lEquals && this.mailHour2 == lTest.mailHour2;
            lEquals = lEquals && this.mailMinutes2 == lTest.mailMinutes2;
            lEquals = lEquals && this.mailHour3 == lTest.mailHour3;
            lEquals = lEquals && this.mailMinutes3 == lTest.mailMinutes3;
            lEquals = lEquals && this.facStdInCall == lTest.facStdInCall;
            lEquals = lEquals && this.facStdOutCall == lTest.facStdOutCall;
            lEquals = lEquals && this.facOutLevel1 == lTest.facOutLevel1;
            lEquals = lEquals && this.facOutLevel2 == lTest.facOutLevel2;
            lEquals = lEquals && this.facOutLevel3 == lTest.facOutLevel3;
            lEquals = lEquals && this.isPriceAgendaFixed == lTest.isPriceAgendaFixed;
            lEquals = lEquals && this.facAgendaCall == lTest.facAgendaCall;
            lEquals = lEquals && this.facFaxCall == lTest.facFaxCall;
            lEquals = lEquals && this.agendaPriceUnit == lTest.agendaPriceUnit;
            lEquals = lEquals && this.facSms == lTest.facSms;
            lEquals = lEquals && this.facCallForward == lTest.facCallForward;
            lEquals = lEquals && this.taskHourRate == lTest.taskHourRate;
            if (this.companyName == null)
            {
                lEquals = lEquals && (lTest.companyName == null);
            }
            else
            {
                lEquals = lEquals && this.companyName.equals(lTest.companyName);
            }
            if (this.attToName == null)
            {
                lEquals = lEquals && (lTest.attToName == null);
            }
            else
            {
                lEquals = lEquals && this.attToName.equals(lTest.attToName);
            }
            if (this.street == null)
            {
                lEquals = lEquals && (lTest.street == null);
            }
            else
            {
                lEquals = lEquals && this.street.equals(lTest.street);
            }
            if (this.city == null)
            {
                lEquals = lEquals && (lTest.city == null);
            }
            else
            {
                lEquals = lEquals && this.city.equals(lTest.city);
            }
            if (this.btwNumber == null)
            {
                lEquals = lEquals && (lTest.btwNumber == null);
            }
            else
            {
                lEquals = lEquals && this.btwNumber.equals(lTest.btwNumber);
            }
            lEquals = lEquals && this.noInvoice == lTest.noInvoice;
            lEquals = lEquals && this.hasSubCustomers == lTest.hasSubCustomers;
            if (this.superCustomer == null)
            {
                lEquals = lEquals && (lTest.superCustomer == null);
            }
            else
            {
                lEquals = lEquals && this.superCustomer.equals(lTest.superCustomer);
            }
            lEquals = lEquals && this.countAllLongCalls == lTest.countAllLongCalls;
            lEquals = lEquals && this.countLongFwdCalls == lTest.countLongFwdCalls;
            lEquals = lEquals && this.noBtw == lTest.noBtw;
            lEquals = lEquals && this.noEmptyMails == lTest.noEmptyMails;
            lEquals = lEquals && this.textMail == lTest.textMail;
            lEquals = lEquals && this.facLong == lTest.facLong;
            lEquals = lEquals && this.facLongFwd == lTest.facLongFwd;
            lEquals = lEquals && this.facTblMinCalls_I == lTest.facTblMinCalls_I;
            lEquals = lEquals && this.facTblStartCost_I == lTest.facTblStartCost_I;
            lEquals = lEquals && this.facTblExtraCost_I == lTest.facTblExtraCost_I;
            lEquals = lEquals && this.facTblMinCalls_II == lTest.facTblMinCalls_II;
            lEquals = lEquals && this.facTblStartCost_II == lTest.facTblStartCost_II;
            lEquals = lEquals && this.facTblExtraCost_II == lTest.facTblExtraCost_II;
            lEquals = lEquals && this.facTblMinCalls_III == lTest.facTblMinCalls_III;
            lEquals = lEquals && this.facTblStartCost_III == lTest.facTblStartCost_III;
            lEquals = lEquals && this.facTblExtraCost_III == lTest.facTblExtraCost_III;
            lEquals = lEquals && this.facTblMinCalls_IV == lTest.facTblMinCalls_IV;
            lEquals = lEquals && this.facTblStartCost_IV == lTest.facTblStartCost_IV;
            lEquals = lEquals && this.facTblExtraCost_IV == lTest.facTblExtraCost_IV;
            lEquals = lEquals && this.isMailInvoice == lTest.isMailInvoice;

            return lEquals;
        }
        else
        {
            return false;
        }
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + (int) id;

        result = 37 * result + ((this.userId != null) ? this.userId.hashCode() : 0);

        result = 37 * result + ((this.password != null) ? this.password.hashCode() : 0);

        result = 37 * result + ((this.fwdNumber != null) ? this.fwdNumber.hashCode() : 0);

        result = 37 * result + ((this.role != null) ? this.role.hashCode() : 0);

        result = 37 * result + ((this.fullName != null) ? this.fullName.hashCode() : 0);

        result = 37 * result + ((this.custFilter != null) ? this.custFilter.hashCode() : 0);

        result = 37 * result + ((this.stateFilter != null) ? this.stateFilter.hashCode() : 0);

        result = 37 * result + ((this.dirFilter != null) ? this.dirFilter.hashCode() : 0);

        result = 37 * result + ((this.lastLogin != null) ? this.lastLogin.hashCode() : 0);

        result = 37 * result + (int) (lastLoginTS ^ (lastLoginTS >>> 32));

        result = 37 * result + (int) (previousLoginTS ^ (previousLoginTS >>> 32));

        result = 37 * result + (isRegistered ? 0 : 1);

        result = 37 * result + (isAutoRelease ? 0 : 1);

        result = 37 * result + (isXmlMail ? 0 : 1);

        result = 37 * result + (is3W ? 0 : 1);

        result = 37 * result + ((this.w3_PersonId != null) ? this.w3_PersonId.hashCode() : 0);

        result = 37 * result + ((this.w3_CompanyId != null) ? this.w3_CompanyId.hashCode() : 0);

        result = 37 * result + ((this.email != null) ? this.email.hashCode() : 0);

        result = 37 * result + ((this.invoiceEmail != null) ? this.invoiceEmail.hashCode() : 0);

        result = 37 * result + ((this.gsm != null) ? this.gsm.hashCode() : 0);

        result = 37 * result + (int) invoiceType;

        result = 37 * result + (int) (lastInvoiceTime ^ (lastInvoiceTime >>> 32));

        result = 37 * result + (int) (lastMailTime ^ (lastMailTime >>> 32));

        result = 37 * result + (int) mailHour1;

        result = 37 * result + (int) mailMinutes1;

        result = 37 * result + (int) mailHour2;

        result = 37 * result + (int) mailMinutes2;

        result = 37 * result + (int) mailHour3;

        result = 37 * result + (int) mailMinutes3;

        result = 37 * result + (int) facStdInCall;

        result = 37 * result + (int) facStdOutCall;

        result = 37 * result + (int) facOutLevel1;

        result = 37 * result + (int) facOutLevel2;

        result = 37 * result + (int) facOutLevel3;

        result = 37 * result + (isPriceAgendaFixed ? 0 : 1);

        result = 37 * result + (int) facAgendaCall;

        result = 37 * result + (int) facFaxCall;

        result = 37 * result + (int) agendaPriceUnit;

        result = 37 * result + (int) facSms;

        result = 37 * result + (int) facCallForward;

        result = 37 * result + (int) taskHourRate;

        result = 37 * result + ((this.companyName != null) ? this.companyName.hashCode() : 0);

        result = 37 * result + ((this.attToName != null) ? this.attToName.hashCode() : 0);

        result = 37 * result + ((this.street != null) ? this.street.hashCode() : 0);

        result = 37 * result + ((this.city != null) ? this.city.hashCode() : 0);

        result = 37 * result + ((this.btwNumber != null) ? this.btwNumber.hashCode() : 0);

        result = 37 * result + (noInvoice ? 0 : 1);

        result = 37 * result + (hasSubCustomers ? 0 : 1);

        result = 37 * result + ((this.superCustomer != null) ? this.superCustomer.hashCode() : 0);

        result = 37 * result + (countAllLongCalls ? 0 : 1);

        result = 37 * result + (countLongFwdCalls ? 0 : 1);

        result = 37 * result + (noBtw ? 0 : 1);

        result = 37 * result + (noEmptyMails ? 0 : 1);

        result = 37 * result + (textMail ? 0 : 1);

        {
            long l = Double.doubleToLongBits(facLong);
            result = 37 * result + (int) (l ^ (l >>> 32));
        }

        {
            long l = Double.doubleToLongBits(facLongFwd);
            result = 37 * result + (int) (l ^ (l >>> 32));
        }

        result = 37 * result + (int) facTblMinCalls_I;

        {
            long l = Double.doubleToLongBits(facTblStartCost_I);
            result = 37 * result + (int) (l ^ (l >>> 32));
        }

        {
            long l = Double.doubleToLongBits(facTblExtraCost_I);
            result = 37 * result + (int) (l ^ (l >>> 32));
        }

        result = 37 * result + (int) facTblMinCalls_II;

        {
            long l = Double.doubleToLongBits(facTblStartCost_II);
            result = 37 * result + (int) (l ^ (l >>> 32));
        }

        {
            long l = Double.doubleToLongBits(facTblExtraCost_II);
            result = 37 * result + (int) (l ^ (l >>> 32));
        }

        result = 37 * result + (int) facTblMinCalls_III;

        {
            long l = Double.doubleToLongBits(facTblStartCost_III);
            result = 37 * result + (int) (l ^ (l >>> 32));
        }

        {
            long l = Double.doubleToLongBits(facTblExtraCost_III);
            result = 37 * result + (int) (l ^ (l >>> 32));
        }

        result = 37 * result + (int) facTblMinCalls_IV;

        {
            long l = Double.doubleToLongBits(facTblStartCost_IV);
            result = 37 * result + (int) (l ^ (l >>> 32));
        }

        {
            long l = Double.doubleToLongBits(facTblExtraCost_IV);
            result = 37 * result + (int) (l ^ (l >>> 32));
        }

        result = 37 * result + (isMailInvoice ? 0 : 1);

        return result;
    }

}
