/*
 * Generated by XDoclet - Do not edit!
 */
package be.tba.ejb.account.interfaces;

/**
 * Primary key for AccountEntity.
 * 
 * @xdoclet-generated at 1-01-15
 */
public class AccountEntityPK extends java.lang.Object implements java.io.Serializable
{
    /**
    * 
    */
    private static final long serialVersionUID = 1L;
    private int _hashCode = 0;
    private StringBuffer _toStringValue = null;

    public int id;

    public AccountEntityPK()
    {
    }

    public AccountEntityPK(int id)
    {
        this.id = id;
    }

    public int getId()
    {
        return id;
    }

    public void setId(int id)
    {
        this.id = id;
        _hashCode = 0;
    }

    public int hashCode()
    {
        if (_hashCode == 0)
        {
            _hashCode += (int) this.id;
        }

        return _hashCode;
    }

    public boolean equals(Object obj)
    {
        boolean eq = true;
        if (obj == null)
        {
            return false;
        }
        if (!(obj instanceof be.tba.ejb.account.interfaces.AccountEntityPK))
            return false;

        be.tba.ejb.account.interfaces.AccountEntityPK pk = (be.tba.ejb.account.interfaces.AccountEntityPK) obj;

        eq = eq && this.id == pk.id;
        return eq;
    }

    /**
     * @return String representation of this pk in the form of
     *         [.field1.field2.field3].
     */
    public String toString()
    {
        if (_toStringValue == null)
        {
            _toStringValue = new StringBuffer("[.");
            _toStringValue.append(this.id).append('.');
            _toStringValue.append(']');
        }

        return _toStringValue.toString();
    }

}
