/*
 * Generated by XDoclet - Do not edit!
 */
package be.tba.ejb.task.interfaces;

/**
 * Data object for TaskEntity.
 *
 * @xdoclet-generated at 1-01-15
 */
public class TaskEntityData extends be.tba.util.data.AbstractData
// implements java.io.Serializable
{
    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private int id;
    private java.lang.String fwdNr;
    private java.lang.String date;
    private long timeStamp;
    private boolean isFixedPrice;
    private double fixedPrice;
    private int timeSpend;
    private java.lang.String description;
    private boolean isRecuring;
    private long stopTime;
    private long startTime;
    private java.lang.String doneBy;
    private int invoiceId;
    private int accountId;

    public TaskEntityData()
    {
    }

    public TaskEntityData(int id, java.lang.String fwdNr, java.lang.String date, long timeStamp, boolean isFixedPrice, double fixedPrice, int timeSpend, java.lang.String description, boolean isRecuring, long stopTime, long startTime, java.lang.String doneBy, int invoiceId, int accountId)
    {
        setId(id);
        setFwdNr(fwdNr);
        setDate(date);
        setTimeStamp(timeStamp);
        setIsFixedPrice(isFixedPrice);
        setFixedPrice(fixedPrice);
        setTimeSpend(timeSpend);
        setDescription(description);
        setIsRecuring(isRecuring);
        setStopTime(stopTime);
        setStartTime(startTime);
        setDoneBy(doneBy);
        setInvoiceId(invoiceId);
        setAccountId(accountId);
    }

    public TaskEntityData(TaskEntityData otherData)
    {
        setId(otherData.getId());
        setFwdNr(otherData.getFwdNr());
        setDate(otherData.getDate());
        setTimeStamp(otherData.getTimeStamp());
        setIsFixedPrice(otherData.getIsFixedPrice());
        setFixedPrice(otherData.getFixedPrice());
        setTimeSpend(otherData.getTimeSpend());
        setDescription(otherData.getDescription());
        setIsRecuring(otherData.getIsRecuring());
        setStopTime(otherData.getStopTime());
        setStartTime(otherData.getStartTime());
        setDoneBy(otherData.getDoneBy());
        setInvoiceId(otherData.getInvoiceId());
        setAccountId(otherData.getAccountId());
    }

    public be.tba.ejb.task.interfaces.TaskEntityPK getPrimaryKey()
    {
        be.tba.ejb.task.interfaces.TaskEntityPK pk = new be.tba.ejb.task.interfaces.TaskEntityPK(this.getId());
        return pk;
    }

    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public java.lang.String getFwdNr()
    {
        return this.fwdNr;
    }

    public void setFwdNr(java.lang.String fwdNr)
    {
        this.fwdNr = fwdNr;
    }

    public java.lang.String getDate()
    {
        return this.date;
    }

    public void setDate(java.lang.String date)
    {
        this.date = date;
    }

    public long getTimeStamp()
    {
        return this.timeStamp;
    }

    public void setTimeStamp(long timeStamp)
    {
        this.timeStamp = timeStamp;
    }

    public boolean getIsFixedPrice()
    {
        return this.isFixedPrice;
    }

    public void setIsFixedPrice(boolean isFixedPrice)
    {
        this.isFixedPrice = isFixedPrice;
    }

    public double getFixedPrice()
    {
        return this.fixedPrice;
    }

    public void setFixedPrice(double fixedPrice)
    {
        this.fixedPrice = fixedPrice;
    }

    public int getTimeSpend()
    {
        return this.timeSpend;
    }

    public void setTimeSpend(int timeSpend)
    {
        this.timeSpend = timeSpend;
    }

    public java.lang.String getDescription()
    {
        return this.description;
    }

    public void setDescription(java.lang.String description)
    {
        this.description = description;
    }

    public boolean getIsRecuring()
    {
        return this.isRecuring;
    }

    public void setIsRecuring(boolean isRecuring)
    {
        this.isRecuring = isRecuring;
    }

    public long getStopTime()
    {
        return this.stopTime;
    }

    public void setStopTime(long stopTime)
    {
        this.stopTime = stopTime;
    }

    public long getStartTime()
    {
        return this.startTime;
    }

    public void setStartTime(long startTime)
    {
        this.startTime = startTime;
    }

    public java.lang.String getDoneBy()
    {
        return this.doneBy;
    }

    public void setDoneBy(java.lang.String doneBy)
    {
        this.doneBy = doneBy;
    }

    public int getInvoiceId()
    {
        return this.invoiceId;
    }

    public void setInvoiceId(int invoiceId)
    {
        this.invoiceId = invoiceId;
    }

    public int getAccountId()
    {
        return this.accountId;
    }

    public void setAccountId(int accountId)
    {
        this.accountId = accountId;
    }
  
    public String toString()
    {
        StringBuffer str = new StringBuffer("{");

        str.append(toNameValueString().toString());
        str.append('}');

        return (str.toString());
    }

    public String toNameValueString()
    {
        StringBuffer str = new StringBuffer();

        str.append("FwdNr='");
        str.append((this.fwdNr != null) ? this.fwdNr : "");
        str.append("',Date='");
        str.append((this.date != null) ? escapeQuotes(this.date) : "");
        str.append("',TimeStamp=");
        str.append(getTimeStamp());
        str.append(",IsFixedPrice=");
        str.append(getIsFixedPrice());
        str.append(",FixedPrice=");
        str.append(getFixedPrice());
        str.append(",TimeSpend=");
        str.append(getTimeSpend());
        str.append(",Description='");
        str.append((this.description != null) ? escapeQuotes(this.description) : "");
        str.append("',IsRecuring=");
        str.append(getIsRecuring());
        str.append(",StartTime=");
        str.append(getStartTime());
        str.append(",StopTime=");
        str.append(getStopTime());
        str.append(",DoneBy='");
        str.append((this.doneBy != null) ? this.doneBy : "");
        str.append("',InvoideId=");
        str.append(getInvoiceId());
        str.append(",AccountID=");
        str.append(getAccountId());
        return (str.toString());
    }

    public String toValueString()
    {
        StringBuffer str = new StringBuffer();

        // "(1, '409031', '04/10/05', 1128528272192, 1, 220, 0, 'Nabelactie voor client'. ',0 ,0 ,0 ,0 ,'', 0)
        str.append("'0','");
        str.append((this.fwdNr != null) ? this.fwdNr : "");
        str.append("','");
        str.append((this.date != null) ? escapeQuotes(this.date) : "");
        str.append("',");
        str.append(getTimeStamp());
        str.append(",");
        str.append(getIsFixedPrice());
        str.append(",");
        str.append(getFixedPrice());
        str.append(",");
        str.append(getTimeSpend());
        str.append(",'");
        str.append((this.description != null) ? escapeQuotes(this.description) : "");
        str.append("',");
        str.append(getIsRecuring());
        str.append(",");
        str.append(getStartTime());
        str.append(",");
        str.append(getStopTime());
        str.append(",'");
        str.append((this.doneBy != null) ? this.doneBy : "");
        str.append("',");
        str.append(getInvoiceId());
        str.append(",");
        str.append(getAccountId());
        return (str.toString());
    }

    public boolean equals(Object pOther)
    {
        if (pOther instanceof TaskEntityData)
        {
            TaskEntityData lTest = (TaskEntityData) pOther;
            boolean lEquals = true;

            lEquals = lEquals && this.id == lTest.id;
            lEquals = lEquals && this.timeStamp == lTest.timeStamp;
            return lEquals;
        }
        else
        {
            return false;
        }
    }

    public int hashCode()
    {
        int result = 17;
        result = 37 * result + (int) id;
        result = 37 * result + (int) (stopTime ^ (stopTime >>> 32));
        return result;
    }

}
